Haaretz/htz-frontend

packages/htz-react-base/babel.js, packages/htz-react-base/package.json, packages/htz-react-base/yarn.lock
=> Add transform-class-properties Babel plugin

packages/htz-components/package.json, packages/htz-react-base/scripts/update-scripts.js
=> Sort package.json:scripts entries in update-scripts

packages/apps/purchase-page/components/LandingHeader/LandingHeader.js, packages/apps/purchase-page/components/OfferPage/Stages/ChooseProductStageElements/OfferList.js, packages/apps/purchase-page/components/OfferPage/Stages/ChooseSlotStage.js, packages/apps/purchase-page/components/OfferPage/Stages/ChooseSlotsStageElements/DesktopView.js, packages/apps/purchase-page/components/OfferPage/Stages/ChooseSlotsStageElements/MobileView.js, packages/apps/purchase-page/components/Redirect/Redirect.js, packages/libs/htz-react-server/src/createContext.js, packages/libs/htz-react-server/src/index.js, packages/libs/htz-react-server/src/routes/purchase.js
affects: @haaretz/purchase-page, @haaretz/htz-react-server
**Notes:**
Design:
Usability:
Tests
=> fix: back and forward buttons should work at the client

packages/apps/purchase-page/components/LandingHeader/LandingHeader.js, packages/apps/purchase-page/layouts/MainLayout.js, packages/components/htz-components/src/components/BI/BIAction.js, packages/components/htz-components/src/components/BI/BIAction.md, packages/components/htz-components/src/components/BI/BIRequest.js, packages/components/htz-components/src/components/BI/BIRequest.md, packages/components/htz-components/src/components/BI/extractParamFromUrl.js, packages/components/htz-components/src/components/BI/statutil.js, packages/components/htz-components/src/components/BI/withTimeout.js, packages/components/htz-components/src/index.js, packages/libs/htz-user-utils/src/service/abuse-service.js
affects: @haaretz/purchase-page, @haaretz/htz-components, @haaretz/htz-user-utils
**Notes:**
Design:
Usability:
Tests
=> feat: add BIAction and BIRequest components

packages/apps/purchase-page/components/OfferPage/Stages/Elements/StageCounter.js, packages/apps/purchase-page/pages/promotions-page/stage1.js, packages/apps/purchase-page/theme/consts/i18n.js, packages/libs/app-utils/src/apollo/createClient.js
affects: @haaretz/purchase-page, @haaretz/app-utils
**Notes:**
Design:
Usability:
Tests
=> fix(promotions page): fix stage number when starts on stage 2

packages/components/htz-components/src/components/BI/statutil.js
**Notes:**
Design:
Usability:
Tests
=> fix: bIStat endpoint change with environment variable

packages/apps/purchase-page/layouts/MainLayout.js, packages/apps/purchase-page/theme/consts/i18n.js
affects: @haaretz/purchase-page
=> feat(purchase-page): add meta tag with google site verification code

packages/apps/purchase-page/pages/promotions-page/stage1.js, packages/apps/purchase-page/pages/promotions-page/stage2.js, packages/libs/htz-react-server/src/routes/purchase.js
refactor server side routing to start at render on the server the correct starting page according to papi pageNumber response
affects: @haaretz/purchase-page, @haaretz/htz-react-server
=> refactor(htz-react-server purchase-page): 

packages/apps/purchase-page/static/robots.txt, packages/libs/htz-react-server/src/routes/purchase.js
affects: @haaretz/purchase-page, @haaretz/htz-react-server
=> feat(purchase-page htz-react-server): add and serve robots.txt file

packages/libs/htz-user-utils/src/service/user-services.js
affects: @haaretz/htz-user-utils
=> refactor(htz-user-utils): update timout func for user services to 8sec

packages/components/htz-components/src/components/List/views/Panucci/Panucci.js, packages/components/tm-theme/src/consts/i18n.js
affects: @haaretz/haaretz.co.il, @haaretz/htz-components
**Notes:**
Design:
Usability:
Tests
=> fix(listviews): fix of panucci listview query

packages/apps/haaretz.co.il/components/HomePage/List/DynamicListView.js, packages/apps/haaretz.co.il/components/HomePage/List/views/Kroker/Kroker.js, packages/components/htz-components/src/index.js
affects: @haaretz/haaretz.co.il
ISSUES CLOSED: #1256
**Notes:**
Design:
Usability:
Tests
=> fix(listviews): export kroker list view to haaretz.co.il

packages/components/htz-components/src/components/List/views/Mousepad/MousepadTeaser.js, packages/components/htz-components/src/components/List/views/Mousepad/MousepadView.js
affects: @haaretz/haaretz.co.il, @haaretz/htz-components
**Notes:**
Design:
Usability:
Tests
=> fix(listviews): mousepad listview design fix (popular)

packages/components/htz-components/src/components/Scripts/GStat.js, packages/components/htz-components/src/components/Scripts/InitPixel.js, packages/components/htz-components/src/createDocument.js
**Notes:**
Design:
Usability:
Tests
=> fix(scripts fix): fix undefined AW and _sf_async_config.domain

packages/apps/haaretz.co.il/layouts/HomePageLayout.js
affects: @haaretz/haaretz.co.il
**Notes:**
Design:
Usability:
Tests
=> feat(ga_homepage_init): homepage init ga and send to page view

packages/components/htz-components/src/components/Ads/AdSlotBase.js, packages/components/htz-components/src/components/Ads/GeneralAdSlot.js, packages/components/htz-components/src/components/List/views/Kroker/KrokerView.js, packages/components/htz-components/src/flowTypes/DfpBannerType.js, packages/libs/app-utils/src/fragments/dfpBanner/dfpBanner.js, packages/libs/app-utils/src/schema/types/dfp_banner_type.js
affects: @haaretz/htz-components, @haaretz/app-utils
**Notes:**
Design:
Usability:
Tests
=> feat(dfp banner): add miscStyles from polopoly

packages/components/htz-components/src/components/PageLayout/slots/Header.js
**Notes:**
Design:
Usability:
Tests
=> fix(htz logo change): revert htz logo

packages/components/htz-components/src/components/Footer/Footer.js, packages/components/htz-components/src/createDocument.js
=> refactor(document): remove chartBeat

packages/components/htz-components/src/components/MarketingNotifications/Strip/StripStyle.js
=> fix(top strip): remove from mobile

packages/components/htz-components/src/components/ArticleTypes/LiveBlogArticle/LiveBlogElements/LiveBlogItem.js
=> refactor(live blog item): enlarge the share buttons

packages/components/htz-components/src/components/Ads/BillboardAdSlot.js
=> refactor(dfp-billboard): fix style

packages/components/htz-components/src/components/Footer/Footer.js, packages/components/htz-components/src/createDocument.js
=> refactor(document): restore chartBreat

packages/components/htz-components/src/components/Masthead/PageDateTime.js, packages/components/htz-components/src/components/Time/Time.js
=> fix(header date-time): use date time from users browser

packages/components/htz-components/src/components/CommentsSection/CommentList.js, packages/components/htz-components/src/components/List/views/Zoidberg/ZoidbergView.js
=> fix(components): change adSlot ids for talkbacks

packages/components/htz-components/src/components/Masthead/PageDateTime.js
=> fix(page date): fix date blink. replace locale

packages/components/htz-components/src/components/Masthead/Masthead.js, packages/components/htz-components/src/components/MobileNavigationMenu/MobileNavigationMain.js
=> fix(article_nav): display nav footer only in article page

packages/components/htz-components/src/components/List/DynamicListView.js, packages/components/htz-components/src/components/List/views/Clampazzo/Clampazzo.js, packages/components/htz-components/src/components/List/views/Clampazzo/ClampazzoView.js, packages/libs/app-utils/src/fragments/teaser/teaser.js, packages/libs/app-utils/src/index.js
affects: @haaretz/htz-components, @haaretz/app-utils
**Notes:**
Usability:
Tests
=> feat(components): new Clampazzo list component for mobile commercial

packages/apps/haaretz.co.il/pages/_app.js, packages/libs/app-utils/src/apollo/createClient.js, packages/libs/htz-react-server/package.json, packages/libs/htz-react-server/src/index.js, yarn.lock
affects: @haaretz/haaretz.co.il, @haaretz/app-utils, @haaretz/htz-react-server
**Notes:**
Usability:
Tests
=> feat(client): add userAgent object to the store

packages/components/htz-components/src/components/MarketingNotifications/BottomStrip/BottomStripStyle.js
=> feat(bottom notification): style adjasments

packages/components/htz-components/src/components/Survey/Survey.js, packages/components/htz-components/src/components/Survey/style.js
=> feat(survey simple): no animation and no vertical support

packages/components/htz-components/src/createDocument.js
=> refactor(document): remove chartBeatMab

packages/components/htz-components/src/components/MarketingNotifications/MiddleRuller/MiddleRullerNotification.js
=> feat: make the all middle ruller clickable

packages/components/htz-components/src/components/List/views/Wong/WongView.js
ISSUES CLOSED: #1604
**Notes:**
Usability:
Tests
=> feat(hompage gallery): fix homepage gallery in main teaser

packages/components/htz-components/package.json, packages/components/htz-components/src/components/Survey/Survey.js, packages/components/htz-components/src/createDocument.js, packages/libs/app-utils/src/apollo/createClient.js, packages/libs/htz-react-server/package.json, packages/libs/htz-react-server/src/routes/htz.js, yarn.lock
affects: @haaretz/htz-components, @haaretz/app-utils, @haaretz/htz-react-server
**Notes:**
Usability:
Tests
=> feat(survey): add view modes (horizental | vetical)

packages/components/htz-components/src/components/ClickTracker/ClickTrackerWrapper.js
=> refactor(click trackers): fix the priorities logic

packages/components/htz-components/src/components/DropdownList/DropdownItem.js, packages/components/htz-components/src/components/Masthead/MastheadUserMenu/MastheadUserMenu.js, packages/components/htz-components/src/components/Masthead/MastheadUserTools.js, packages/components/htz-components/src/components/NavigationMenu/NavigationMenu.js, packages/components/htz-theme/src/consts/i18n.js
affects: @haaretz/htz-components, @haaretz/htz-theme
**Related issue(s):** #1548 
**Notes:**
Usability:
Tests
=> feat(bi_actions_masthead): adding bi actions to masthead navigation

packages/components/htz-components/src/components/Survey/Survey.js, packages/components/htz-components/src/components/Survey/style.js, yarn.lock
=> feat: surveys phase 3 animation support

packages/components/htz-components/src/components/TableScore/NBATableScore/NBATable.js, packages/components/htz-components/src/components/TableScore/SoccerTableScore/SoccerGroups/SoccerGroupsTable.js, packages/components/htz-components/src/components/TableScore/SoccerTableScore/SoccerLeagues/SoccerLeaguesTable.js
=> fix(table score): fix import error

packages/apps/haaretz.co.il/layouts/HomePageLayout.js
=> fix(homepagelayout component): add a / sign to alternate url

packages/components/htz-components/src/components/UserAgent/UserAgent.js
=> refactor(user agent): add console log at the conditions check

packages/apps/haaretz.co.il/components/HomePage/MainSlot.js, packages/apps/haaretz.co.il/flowTypes/MainSlotType.js, packages/apps/haaretz.co.il/layouts/queries/homepage_layout.js, packages/components/htz-components/src/components/Image/Image.js, packages/components/htz-components/src/components/Image/Picture.js, packages/components/htz-components/src/components/RssFeed/RssFeed.js, packages/components/htz-components/src/flowTypes/ImageDataType.js, packages/components/htz-components/src/flowTypes/RssFeedType.js, packages/components/htz-components/src/index.js, packages/components/htz-components/src/utils/componentFromInputTemplate.js, packages/components/htz-components/src/utils/validateType.js, packages/libs/app-utils/src/schema/getSchema.js, packages/libs/app-utils/src/schema/types/home_page_main_type.js, packages/libs/app-utils/src/schema/types/rss_feed_item_type.js, packages/libs/app-utils/src/schema/types/rss_feed_type.js
affects: @haaretz/haaretz.co.il, @haaretz/htz-components, @haaretz/app-utils
**Notes:**
Usability:
Tests
=> feat(rss feed onlife): rss feed component based on morbo list-view

packages/apps/haaretz.co.il/components/GoogleAnalyticsHomePage/GoogleAnalyticsHomePage.js, packages/apps/haaretz.co.il/components/HomePage/SlotsLayout.js, packages/apps/haaretz.co.il/layouts/HomePageLayout.js, packages/components/htz-components/src/components/Footer/Footer.js, packages/components/htz-components/src/components/GoogleAnalytics/GaHomePage.js, packages/components/htz-components/src/index.js
affects: @haaretz/haaretz.co.il, @haaretz/htz-components
**Notes:**
Usability:
Tests
=> fix(ga_gstat): GStat no ssr wrapper and GA dynamic import ssr false

packages/libs/app-utils/src/schema/types/new_vote_response_type.js
valid response for comments vote in network
affects: @haaretz/app-utils
comments
**Related issue(s):** #1648 
**Notes:**
Usability:
Tests
=> fix(new_vote_response): fix status type to get valid response

packages/components/htz-components/src/components/RssFeed/RssFeed.js, packages/components/htz-components/src/components/Teaser/Teaser.js, packages/components/htz-components/src/components/TeaserHeader/TeaserHeader.js, packages/components/htz-components/src/components/TeaserMedia/TeaserMedia.js, packages/components/htz-components/src/flowTypes/TeaserDataType.js
=> fix(link target): fix link-target for teaser-data and rss

packages/components/htz-components/src/components/Embed/__tests__/__snapshots__/Youtube.test.js.snap, packages/components/htz-components/src/components/Embed/elements/Youtube.js
=> feat(youtube-embed-display): support a vertical view for YouTube embeds

packages/components/htz-components/src/components/Masthead/HomePageMasthead.js, packages/components/htz-components/src/components/Masthead/LogoAndDate.js, packages/components/htz-components/src/components/Masthead/MastheadWrapper.js
=> feat(masthead logo): fade out and in when search opens/closes

packages/components/htz-components/src/components/Alerts/Alerts.js, packages/components/htz-components/src/components/Alerts/AuthorAlert.js, packages/components/htz-components/src/components/ArticleHeader/ArticleHeaderMeta.js, packages/components/htz-components/src/components/ServiceByMailRegistration/AuthorNotificationsRegistration.js, packages/components/htz-components/src/components/ServiceByMailRegistration/ServiceByMailRegistration.js
**Notes:**
Design is not ready yet.
Design:
Usability:
Tests
=> feat(author alert): Author alert modal 

packages/components/htz-components/src/components/Ads/WebInreadAdSlot.js, packages/components/htz-components/src/components/Ads/WebInreadAdSlotCaption.js, packages/libs/dfp/package.json, packages/libs/dfp/src/objects/adManager.js
affects: @haaretz/htz-components, @haaretz/dfp
**Notes:**
Usability:
Tests
=> feat(dfp, components): display or hide ad caption depending on ad size

packages/components/htz-components/src/components/Ads/DynamicAds/DynamicSlotFromDfpConfig.js, packages/components/htz-components/src/components/Ads/utils/getSectionsFromLineage.js, packages/components/htz-components/src/components/List/views/Zoidberg/ZoidbergView.js
=> feat(components): zoidberg list will use DynamicSlotFromDfpConfig

packages/components/htz-components/src/components/Survey/Survey.js, packages/components/htz-components/src/components/Survey/style.js
=> feat(survey): wrap the date of the legend with b tag

packages/components/htz-components/src/components/List/views/Morbo/MorboView.js
=> fix(morbo fix): fix morbo view style

packages/components/htz-components/src/components/List/views/Sal/SalView.js, packages/components/htz-components/src/components/RssFeed/RssFeed.js
=> feat(sal listview): sal listview for onlife rss feed

packages/apps/login/components/Misc/Forms/IndexForm.js, packages/apps/login/components/Misc/Forms/OtpForm.js, packages/apps/login/components/Misc/Forms/PasswordForm.js, packages/apps/login/pages/loginForms.js, packages/apps/login/pages/queries/UserQueries.js, packages/apps/login/pages/queryutil/userDetailsOperations.js, packages/apps/login/util/debtCheckUtil.js
=> App/login debt user 1.0

packages/components/htz-components/src/components/CommentsSection/ApolloWrappedComments.js, packages/components/htz-components/src/components/CommentsSection/queries/fetchComments.js, packages/components/htz-components/src/components/CommentsSection/queries/getLineage.js
=> fix(comments fetch fix): lineage query added before fetch comments query

docker-compose-login-prod.yml
affects: @haaretz/login
**Notes:**
Usability:
Tests
=> fix(login): set google acounts id on enviroment config

packages/components/htz-components/src/components/Survey/Pie.js, packages/components/htz-components/src/components/Survey/Survey.js, packages/components/htz-components/src/components/Survey/style.js, packages/components/htz-theme/src/consts/i18n.js, packages/components/htz-theme/src/htzTheme.js
affects: @haaretz/htz-components, @haaretz/htz-theme
**Notes:**
Usability:
Tests
=> feat: blocks pie chart

packages/apps/haaretz.co.il/utils/getArticlePageElements.js
affects: @haaretz/haaretz.co.il
**Notes:**
Usability:
Tests
=> feat(clampazzo-listview): add support for clampazzo in article pages
